server {
  listen 8080;
  resolver 169.254.169.254 valid=10s ipv6=off;

  location /auth/ {
    set $upstream auth-service:4000;
    proxy_pass http://$upstream/;
  }

  location /profile/ {
    set $upstream profile-service:4001;
    proxy_pass http://$upstream/;
  }

  location /projects/ {
    set $upstream projects-service:4002;
    proxy_pass http://$upstream/;
  }

  location /blog/ {
    set $upstream blog-service:4003;
    proxy_pass http://$upstream/;
  }

  location /cv/ {
    set $upstream cv-service:4004;
    proxy_pass http://$upstream/;
  }
}
