upstream auth_service {
  server auth-service:4000;
}

upstream profile_service {
  server profile-service:4001;
}

upstream projects_service {
  server projects-service:4002;
}

upstream blog_service {
  server blog-service:4003;
}

upstream cv_service {
  server cv-service:4004;
}

server {
  listen 8080;

  location /auth/ {
    proxy_pass http://auth_service/;
  }

  location /profile/ {
    proxy_pass http://profile_service/;
  }

  location /projects/ {
    proxy_pass http://projects_service/;
  }

  location /blog/ {
    proxy_pass http://blog_service/;
  }

  location /cv/ {
    proxy_pass http://cv_service/;
  }
}
